// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL8_TPVurPgvOSRQ2rshqhsg-o_qvDxa8',
    appId: '1:97204161956:web:e62553c46b9be3135a0531',
    messagingSenderId: '97204161956',
    projectId: 'winedine-81337',
    authDomain: 'winedine-81337.firebaseapp.com',
    storageBucket: 'winedine-81337.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKUFZ07KnvBFK0ecBFLK1eHXVli82Lnps',
    appId: '1:97204161956:android:b5882023ab4539dd5a0531',
    messagingSenderId: '97204161956',
    projectId: 'winedine-81337',
    storageBucket: 'winedine-81337.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6ym2Gus9rYKVIM8EhZI9TeGYyIobZVm0',
    appId: '1:97204161956:ios:f2cd3bec29a9c79d5a0531',
    messagingSenderId: '97204161956',
    projectId: 'winedine-81337',
    storageBucket: 'winedine-81337.appspot.com',
    iosClientId: '97204161956-5333hl5o67mp0so2tr763tj4duckqt4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.winedine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6ym2Gus9rYKVIM8EhZI9TeGYyIobZVm0',
    appId: '1:97204161956:ios:f2cd3bec29a9c79d5a0531',
    messagingSenderId: '97204161956',
    projectId: 'winedine-81337',
    storageBucket: 'winedine-81337.appspot.com',
    iosClientId: '97204161956-5333hl5o67mp0so2tr763tj4duckqt4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.winedine',
  );
}
